### PR TITLE
Adding Sandhisplitter Layer

### PR DESCRIPTION
**Pull request by jerinphilip**
Enhancing spellchecker to handle agglutination to some extent.

### CODE REVIEW

**Comment by copyninja** [comment]
All tests fail eh?.. Please have a look at it

**Comment by jerinphilip** [comment]
How do I rerun the test?  Test fail here again due to rreplace -> setupfiles. Should be okay once @balasankarc commits are in.

**Comment by balasankarc** [comment]
@jerinphilip You can't. @copyninja  has to re-run the Builds. :(

**Comment by copyninja** [comment]
I've put rebuilds let us see how it goes.

**Comment by copyninja** [comment]
@jerinphilip Builds fail. It breaks on some tests. Please fix them. I'm not sure if fixing is on your side or @balasankarc side.

**Comment by balasankarc** [comment]
@copyninja Not mine. :D . I stopped at my last PR which build fine. ;)

@jerinphilip When you changed the Malayalam class to BaseMalayalam, I believe you should probably tweak the tests to reflect that change.

**Comment by jerinphilip** [comment]
@copyninja: Any idea why the travis build is failing? Circle CI and tox on my machine seem to be working fine.

**Comment by copyninja** [comment]
Some times travis behaves weirdly. I've put it for rebuild. Anyway I will merge the PR. Also one question did you consider all modules supporting REST?.. I see only a few modules listed in your blog compared with list here http://libindic.org/

**Comment by jerinphilip** [comment]
@copyninja: I prioritized in order of use as a product. Few modules which were being developed on are left untouched. I also have the question if indic-trans is going to replace Transliteration.

The ones I believe missing from libindic.org list are stemmer, syllabifier and transliteration, three which are under development. 

Regarding ngram and w-shingling, I am hoping to a few discussions affecting these modules which would bring changes to the API.

**Comment by copyninja** [comment]
Ah okay. Can we continue this discussion on list?. Yes My intention is to replace transliteration with indic-trans as it is much much better than our version.  Fair enough you did not touch things which are under development.

Lets discuss remaining things over mail.

**Pull request merged**
