### PR TITLE
Use CI and coverage information of libindic repo in readme

### PR DESCRIPTION
**Pull request by balasankarc**
Update readme with link to coverage and travis results of libindic repo instead of my personal fork.

### CODE REVIEW

**Comment by balasankarc** [comment]
@copyninja This will point everything to libindic repo.

**Comment by copyninja** [comment]
Can you also fix circle.yml. Guess indentation is messed up a bit.

**Comment by balasankarc** [comment]
@copyninja Done.

**Comment by balasankarc** [comment]
@copyninja Any idea why Travis fails? It builds fine for my [personal fork](https://travis-ci.org/balasankarc/spellchecker). i didn't understand the log.

**Pull request merged**
