### PR TITLE
Consider inflections during spellcheck

### PR DESCRIPTION
**Pull request by balasankarc**
This is a major pull request as part of GSoC work. PRs after polishing the codebase will follow.

#### Changes
 * Handle inflections that may arise in words before spellchecking
 * Generate suggestions that match the original input word's inflected form
 * Change package structure to `libindic.module`
 * Add tests, switch to testrepository for running tests
 * Use pbr for packaging
 * Add CI integration and coverage report generation

### CODE REVIEW

**Comment by copyninja** [comment]
Travis and Circle Integration?..

**Comment by balasankarc** [comment]
@copyninja Ah. I had a feeling I forgot something. Will add Circle (Travis is already there, next push will initiate a build. Also, please add this repo to coveralls)

**Comment by copyninja** [comment]
Balasankar C <notifications@github.com> writes:

> @copyninja Ah. I had a feeling I forgot something. Will add Circle
> (Travis is already there, next push will initiate a build. Also,
> please add this repo to coveralls)
>

Never mind I added Circle.yml already. And I think coveralls is already
present right?.. I see the badge.

**Comment by balasankarc** [comment]
> And I think coveralls is already present right?.. I see the badge.

No. That is from my fork. Once the libindic one is added to coveralls, I'll edit the readme to display that result.

**Comment by copyninja** [comment]
Balasankar C <notifications@github.com> writes:

>     And I think coveralls is already present right?.. I see the badge.
>
> No. That is from my fork. Once the libindic one is added to coveralls,
> I'll edit the readme to display that result.
>

Ah okay let me do that then.

**Pull request merged**
